### ISSUE TITLE
Market calculations off

### ISSUE THREAD

**Issue by rennai76** [Kurt-Midas/Gadgets-Node#1]
Playing around with either having a single planet import P3 production or a 5 planet P3 production (where I'd make all necessary P0 P1 and P2) I noticed something odd in the profit calculations.  Importing the goods resulted in more than twice the projected profit per hour. I [set up a spreadsheet](https://drive.google.com/open?id=1zlMYwxF5Xf57ZkQVSWl11tI-dy_4RwDGrZaBwqYFRwE) looking at all the variables to see what I'm missing, and can't figure out how the 5-planet setup is actually calculated. Shouldn't the 5-planet setup be more profitable since you are not replying on market prices to get obtain the goods?  Here's the two setups:

5 planet production: http://evegadgets.com/#/pi/5730c1757ec832090c9426ef

Single planet import: http://evegadgets.com/#/pi/5730c1727ec832090c9426ea

**Comment by Kurt-Midas** [comment]
Looking at those two setups, I see half the "average profit per hour" on
the full setup but considerably higher "profit per hour."  If you look at
the Planet 8 independent view, it looks identical to the complete view on
the single-planet setup.

That said, I see several problems with my calculations. They appear to
mostly cancel (except market fees) but I need to do some cleanup. Thanks
for bringing this to my attention.

**Comment by rennai76** [comment]
No no, thank you for writing such a great program! I'm happy to help where I can.

My impression is the only thing that should change where the materials are coming from (no market purchases for the import items but still have the export/import POCO fees, thus different overall ISK/hour calculation).  I think you see what I see - half the profit for making your own materials instead of buying the materials from the market. It seems to me it should be the other way around. By making my own materials for the final product I lower my overhead. I can only make 9 units per hour on both setups, but I don't pay anyone for the materials in the "production" setup.

One other related potential issue: If you duplicate the single planet the overall ISK/hour calculation doesn't increase.  If I'm making a 20% profit from the P2 materials I buy, I would expect my overall ISK/hour to increase proportionately.  E.G. if one planet is making 700k/hour, the system setup of 5 of those planets should be netting 3500k/hour.  The calculations in Eve Gadget show 700k/hour no matter how many planets you make copies of.

Please keep up the great work! If you don't mind me bugging you then I'll keep posting bugs if/when I see them.  Also, let me know if/how/when I can help!

**Comment by Kurt-Midas** [comment]
What I'm seeing is that I'm including both all the imports and all the
exports in the summary view, including intermediate products that the total
setup both produces and consumes. That largely cancels apart from the
market fees.

The "half profit" you're seeing is average profit. The factory planet is
quite profitable but everything else is considerably less so (your lowest
profit planet is around 110k). Unless I'm badly mistaken the actual line
you want is the second from the bottom. That would solve the "copied
planets not increasing your average profit" issue too.

Please keep reporting anything you find or features you'd like to see. I
built this for other capsuleers and to have one helping out or offering
ideas for new features or even new projects is immensely satisfying.

**Comment by rennai76** [comment]
You are correct! I completely missed the "average" and was just going with the bottom line. I potentially have some ideas in mind to flesh out and will run them by you later.  Thank you!

**Comment by Kurt-Midas** [comment]
Fixed and deployed. Verified on live, closing issue.
